import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import 'cv_pdf_styles.dart';
import 'cv_pdf_theme.dart';

class CvPdfSections {
  CvPdfSections._();

  static pw.Widget header({
    required String fullName,
    required String jobTitle,
    required String email,
    required String phone,
    required String address,
  }) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(18),
      decoration: pw.BoxDecoration(
        color: CvPdfTheme.primary,
        borderRadius: pw.BorderRadius.circular(14),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            fullName.isEmpty ? "Your Name" : fullName,
            style: CvPdfStyles.title().copyWith(
              color: PdfColors.white,
            ),
          ),
          pw.SizedBox(height: 6),
          pw.Text(
            jobTitle.isEmpty ? "Professional Title" : jobTitle,
            style: CvPdfStyles.subtitle().copyWith(
              color: PdfColors.white,
            ),
          ),
          pw.SizedBox(height: 12),
          pw.Text(
            "$email  |  $phone  |  $address",
            style: CvPdfStyles.body().copyWith(
              color: PdfColors.white,
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget heading(String title) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 8),
      child: pw.Text(
        title.toUpperCase(),
        style: CvPdfStyles.heading().copyWith(
          color: CvPdfTheme.primary,
        ),
      ),
    );
  }

  static pw.Widget divider() {
    return pw.Divider(
      thickness: 0.7,
      color: CvPdfTheme.divider,
    );
  }

  static pw.Widget footer() {
    return pw.Center(
      child: pw.Text(
        "Generated by Smart CV",
        style: CvPdfStyles.body().copyWith(
          color: CvPdfTheme.secondary,
        ),
      ),
    );
  }
}